server:
  port: 8081
  
spring:

  datasource:
    dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    url: jdbc:mysql://localhost/haytap?useUnicode=yes&characterEncoding=UTF-8
    username: ersen
    password: 123456
    initialize: false

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLInnoDBDialect
      ddl-auto: update
      show_sql: true