server:
  port: 8080

spring:

  datasource:
    dataSourceClassName: org.h2.Driver
    url: jdbc:h2:mem:haytap
    username: sa
    password: 
    initialize: false

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: create
      show_sql: true
      

  h2:
    console:
      enabled: true
      path: /h2